### ISSUE TITLE
Constantly dropped error in HB logs

### ISSUE THREAD

**Issue by Jerfly-wow** [insaneKane/simpl#8]
I had this posted in the issue around Bloodlust tracking, which seizes up the bot, but I'm sure they're unrelated now. 

Moving to a new issue. 

This issue isn't a blocker, the bot continues to work, it just appears constantly in my HB logs around every 1.3 seconds. 

## Constant error:
```
[01:13:32.706 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:32.962 N] <16:20>:avgIte: 13.1355555555556
[01:13:34.110 N] Final Verdict
[01:13:34.110 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
```

## Longer log showing how often the error iterates
```
[01:13:34.110 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:35.547 N] Crusader Strike
[01:13:35.547 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:35.547 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:36.925 N] Exorcism
[01:13:36.925 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:36.925 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:38.317 N] Judgment
[01:13:38.317 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:38.317 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:39.667 N] Crusader Strike
[01:13:39.667 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:39.667 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:41.049 N] Final Verdict
[01:13:41.049 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:41.049 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:42.434 N] Exorcism
[01:13:42.435 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:42.435 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:43.795 N] Crusader Strike
[01:13:43.795 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:43.795 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:45.177 N] Judgment
[01:13:45.177 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:45.177 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:46.553 N] Final Verdict
[01:13:46.553 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:46.553 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:47.942 N] Crusader Strike
[01:13:47.942 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:47.942 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:49.439 N] Exorcism
[01:13:49.439 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:49.439 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:50.807 N] Judgment
[01:13:50.807 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:50.807 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:51.815 N] <16:20>:avgIte: 13.0632432432432
[01:13:52.185 N] Crusader Strike
[01:13:52.186 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:52.186 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:53.541 N] Final Verdict
[01:13:53.541 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:53.541 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:54.924 N] Exorcism
[01:13:54.924 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:54.924 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:56.296 N] Crusader Strike
[01:13:56.296 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
[01:13:56.296 D] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
   at CallSite.Target(Closure , CallSite , Object , UInt32 )
   at Simcraft.SimcraftImpl.UNIT_SPELLCAST_SUCCEEDED(Object sender, LuaEventArgs args) in C:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 495
   at Styx.WoWInternals.LuaEvents.( , UInt32 , UInt32 , Object[] )
[01:13:57.691 N] Judgment
[01:13:57.691 D] Exception in lua event handler UNIT_SPELLCAST_SUCCEEDED
```

**Comment by insaneKane** [comment]
This should be fixed, probably has been for a while :)
