### ISSUE TITLE
Error, empty profile selection list, after HB updated on 3/11/2015

### ISSUE THREAD

**Issue by Jerfly-wow** [insaneKane/simpl#9]
FYI, Honorbuddy updated tonight. Since then even with a new install of HB I'm getting errors on the Simcraft profile loading screen that prevent it from running.

## Error dialog during profile selection (details button):
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Compiler Errors :

   at Simcraft.APL.RuntimeCodeCompiler.CompileCode(String code) in c:\Honorbuddy\Bots\Simcraft\APL\RuntimeCodeCompiler.cs:line 78
   at Simcraft.SimcraftImpl.GenerateApls(String folder) in c:\Honorbuddy\Bots\Simcraft\SimcraftTop.cs:line 362
   at Simcraft.ProfileSelector.OnShown(EventArgs e) in c:\Honorbuddy\Bots\Simcraft\ProfileSelector.cs:line 31
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Honorbuddy
    Assembly Version: 2.5.13198.772
    Win32 Version: 2.5.13198.772
    CodeBase: file:///C:/Honorbuddy/Honorbuddy.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Tripper.Tools
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Honorbuddy/Tripper.Tools.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
GreyMagic
    Assembly Version: 2.5.13198.772
    Win32 Version: 
    CodeBase: file:///C:/Honorbuddy/GreyMagic.DLL
----------------------------------------
Tripper.RecastManaged
    Assembly Version: 1.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Honorbuddy/Tripper.RecastManaged.DLL
----------------------------------------
{6a64e8cd-2168-4ef4-9ad0-78b96963e2e8}
    Assembly Version: 0.0.0.0
    Win32 Version: 2.5.13198.772
    CodeBase: file:///C:/Honorbuddy/Honorbuddy.exe
----------------------------------------
PresentationFramework.Aero
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.92.0
    Win32 Version: 1.0.92.0
    CodeBase: file:///C:/Honorbuddy/System.Data.SQLite.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
RemoteASM
    Assembly Version: 2.5.13198.772
    Win32 Version: 2.5.13198.772
    CodeBase: file:///C:/Honorbuddy/RemoteASM.DLL
----------------------------------------
RemoteASMNative
    Assembly Version: 2.5.13198.772
    Win32 Version: 
    CodeBase: file:///C:/Honorbuddy/RemoteASMNative.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
5tmbe1hb
    Assembly Version: 1.0.0.0
    Win32 Version: 2.5.13198.772
    CodeBase: file:///C:/Honorbuddy/Honorbuddy.exe
----------------------------------------
Refreshment_1786191556
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Honorbuddy/CompiledAssemblies/Refreshment_1786191556.dll
----------------------------------------
Combat_1827485445
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Honorbuddy/CompiledAssemblies/Combat_1827485445.dll
----------------------------------------
RaidBot_798422072
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Honorbuddy/CompiledAssemblies/RaidBot_798422072.dll
----------------------------------------
Simcraft_1704425814
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Honorbuddy/CompiledAssemblies/Simcraft_1704425814.dll
----------------------------------------
ItemForAuraQuestHelper_1207614875
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Honorbuddy/CompiledAssemblies/ItemForAuraQuestHelper_1207614875.dll
----------------------------------------
Anti Drown_1131865918
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Honorbuddy/CompiledAssemblies/Anti%20Drown_1131865918.dll
----------------------------------------
DrinkPotions_1675250131
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Honorbuddy/CompiledAssemblies/DrinkPotions_1675250131.dll
----------------------------------------
NUuvddSMcSdLtjQXOIDOCdPjPYLq
    Assembly Version: 0.0.0.0
    Win32 Version: 2.5.13198.772
    CodeBase: file:///C:/Honorbuddy/Honorbuddy.exe
----------------------------------------
Singular_2056988375
    Assembly Version: 4.0.0.4449
    Win32 Version: 4.0.0.4449
    CodeBase: file:///C:/Honorbuddy/CompiledAssemblies/Singular_2056988375.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
e4tlfwut
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/scrubbed/AppData/Local/Temp/e4tlfwut.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

## Error in HB window:
```
Please wait a few seconds while Honorbuddy initializes.
Looking for db.dbc in C:\Honorbuddy and all its Subdirectories
ItemForAura - Questhelper - Version 2.0 Loaded.
Count 8441
Aura pre_steady_focus initialized with null
Aura bloodlust_proxy initialized with null
Aura potion_buff initialized with null
Aura anytrinket_buff initialized with null
Aura casting_debuff initialized with null
Aura pre_steady_focus initialized with null
Aura bloodlust_proxy initialized with null
Aura potion_buff initialized with null
Aura anytrinket_buff initialized with null
Streamed store botbases:
	* Enyo (Buddystore)
New bot added!: ArchaeologyBuddy
New bot added!: BGBuddy
New bot added!: Dungeonbuddy
New bot added!: Gatherbuddy2
New bot added!: ProfessionBuddy
New bot added!: Grind Bot
New bot added!: Questing
New bot added!: Mixed Mode
New bot added!: Party Bot
New bot added!: [BETA] GrindBuddy
New bot added!: Combat Bot
New bot added!: Raid Bot
New bot added!: Simcraft Impl
New bot added!: Enyo (Buddystore)
[Singular] Context: using Instances behaviors since inside an instance
[Singular] Starting Singular v4.0.0.4449 
[Singular] Installation: integrity verified for 4.0.0.4449
[Singular] Determining talent spec. 
[Singular] Current spec is  Retribution
[Singular] Context: using Instances behaviors since inside an instance 
[Singular] Your Level 100 Tauren Retribution Paladin Build is
[Singular] ... running the Enyo (Buddystore) bot in Blackrock Foundry [Difficulty 15 Undefined] 
[Singular] ... Raid using my INSTANCES Behaviors in a group of 18
[Singular] ... in a group as DAMAGE role with 18 of 18 players 
[Singular] Pull More: disabled, only Enyo (Buddystore) will Pull targets
[Singular] Initialization complete! 
Installed plugins
    Anti Drown - Enabled
    BuddyMonitor - Disabled
    DrinkPotions - Disabled
    Questhelper - ItemForAura - Enabled
    Refreshment Detection - Enabled
Honorbuddy Startup Complete
[Singular] Your Level 100 Tauren Retribution Paladin Build is
[Singular] ... running the Simcraft Impl bot in Blackrock Foundry [Difficulty 15 Undefined] 
[Singular] ... Raid using my INSTANCES Behaviors in a group of 18
[Singular] ... in a group as DAMAGE role with 18 of 18 players 
Starting the bot!
Currently Using BotBase : Simcraft Impl
Current zone is Blackrock Foundry ([url=http://wowhead.com/zone=6967]Blackrock Foundry - Zone - World of Warcraft[/url])
<5:37 PM>:Loading configuration
<5:37 PM>:Configuration successfully loaded.
Changing current profile to Empty Profile
<17:37>:Compiling Action Lists
<17:37>:New Apl: Paladin_Retribution_T17H
<17:37>:Line 123,30	: The best overloaded method match for 'Simcraft.SimcraftImpl.Cast(string, Styx.TreeSharp.CanRunDecoratorDelegate, Simcraft.SimcraftImpl.GetUnitDelegate, string)' has some invalid arguments - line c:\Users\scrubbed\AppData\Local\Temp\ud5h5i4j.0.cs(123,30) : error CS1502: The best overloaded method match for 'Simcraft.SimcraftImpl.Cast(string, Styx.TreeSharp.CanRunDecoratorDelegate, Simcraft.SimcraftImpl.GetUnitDelegate, string)' has some invalid arguments

<17:37>:Line 123,95	: Argument 3: cannot convert from 'Styx.WoWInternals.WoWObjects.WoWUnit' to 'Simcraft.SimcraftImpl.GetUnitDelegate' - line c:\Users\scrubbed\AppData\Local\Temp\ud5h5i4j.0.cs(123,95) : error CS1503: Argument 3: cannot convert from 'Styx.WoWInternals.WoWObjects.WoWUnit' to 'Simcraft.SimcraftImpl.GetUnitDelegate'
```

**Comment by insaneKane** [comment]
Update please, should be fixed

**Comment by Jerfly-wow** [comment]
Confirmed
